import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "E-Pandayalita",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  }
};

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-merriweather",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={merriweather.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
